### ISSUE TITLE
cannot import name 'get_course_specific_language_choices'

### ISSUE THREAD

**Issue by inducer** [inducer/relate#409]
@dzhuang Something between ee69754 and c5b79ac has just massively wrecked an attempt to deploy current master for me:

```
Traceback:  

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/utils/deprecation.py" in __call__
  138.             response = self.process_request(request)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/middleware/locale.py" in process_request
  24.         i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/conf/urls/i18n.py" in is_language_prefix_patterns_used
  29.     for url_pattern in get_resolver(urlconf).url_patterns:

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/urls/resolvers.py" in url_patterns
  405.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/urls/resolvers.py" in urlconf_module
  398.             return import_module(self.urlconf_name)

File "/usr/lib/python3.6/importlib/__init__.py" in import_module
  126.     return _bootstrap._gcd_import(name[level:], package, level)

File "./relate/urls.py" in <module>
  39. import course.versioning

File "./course/versioning.py" in <module>
  54. from course.utils import (

Exception Type: ImportError at /course/cs357-f17/
Exception Value: cannot import name 'get_course_specific_language_choices'
Request information:
USER: [unable to retrieve the current user]
```

**Comment by inducer** [comment]
It looks like an import loop, though I can't find what's causing it.

```
USER: [unable to retrieve the current user]
```

is also suspicious.

**Comment by inducer** [comment]
Restarted the server, again... Not sure it's still there.

**Comment by dzhuang** [comment]
That's interesting. I noticed it passed tests on your Gitlab instance.

**Comment by inducer** [comment]
Nvm. I don't think this was real. I may have been too hasty, and the git operation may have raced with the server restart, due to heavy I/O load from a DB upgrade.

**Comment by inducer** [comment]
> from a DB upgrade

Much of the reason appears to have been that the DB is offline currently. The error messages aren't exactly helpful though...
